name: digitalinvitationaksala
description: "Akbar & Wulan Weeding Invitation by Aksala Creative Media"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  url_launcher: ^6.2.2
  intl: ^0.19.0
  audioplayers: ^5.2.1
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  lottie: ^3.0.0
  just_audio: ^0.10.5
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/

