// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgPVY0QK6qPM5FbbbX_pNmpm3tl6Ssp7I',
    appId: '1:425075701231:web:783bc0553ed9653c96b21a',
    messagingSenderId: '425075701231',
    projectId: 'aksalainvite',
    authDomain: 'aksalainvite.firebaseapp.com',
    storageBucket: 'aksalainvite.firebasestorage.app',
    measurementId: 'G-JSE48VPDD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDU0HoWOvn3hCeGNYZ9GJPnyhLAdbXqU',
    appId: '1:425075701231:android:6bea012cb594188596b21a',
    messagingSenderId: '425075701231',
    projectId: 'aksalainvite',
    storageBucket: 'aksalainvite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCriwbFToUxCXiIeeV8oVyGt68By0lNb5c',
    appId: '1:425075701231:ios:95c5786fa800ffb696b21a',
    messagingSenderId: '425075701231',
    projectId: 'aksalainvite',
    storageBucket: 'aksalainvite.firebasestorage.app',
    iosBundleId: 'com.example.digitalinvitationaksala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCriwbFToUxCXiIeeV8oVyGt68By0lNb5c',
    appId: '1:425075701231:ios:95c5786fa800ffb696b21a',
    messagingSenderId: '425075701231',
    projectId: 'aksalainvite',
    storageBucket: 'aksalainvite.firebasestorage.app',
    iosBundleId: 'com.example.digitalinvitationaksala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgPVY0QK6qPM5FbbbX_pNmpm3tl6Ssp7I',
    appId: '1:425075701231:web:825b98b676aed09696b21a',
    messagingSenderId: '425075701231',
    projectId: 'aksalainvite',
    authDomain: 'aksalainvite.firebaseapp.com',
    storageBucket: 'aksalainvite.firebasestorage.app',
    measurementId: 'G-TZV2LSV7FV',
  );
}
